on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - uses: npm/action-setup@v2
        with:
          version: 8.4.0
      - run: npm install --frozen-lockfile
      - run: npm run build
      - run: npm test
      - run: npm run check-format
      - run: npm run lint
